add auth domain layer
Pogchamb/github_integration_proj pull request #1
Opened 2023-02-16 08:44 UTC by Pogchamb

2023-02-16 08:51 UTC, Puyre commented
Смотри пачан

1. Давай сделаем разделение по фичам. Добавляешь в рут проекта папку features. В ней папка auth. В каждой папки фичи четыре папки - data, domain, presentation, di
2. Перетаскиваешь все что связано с аторизацией туда
3. Делаешь отдельное апи чисто под авторизацию (потом будет отдельное под список репозиториев)
4. Апи, репу и дс переназываешь с Git[сущность] в Auth[Сущность]

2023-02-16 08:53 UTC, Puyre requested changes

2023-02-16 08:53 UTC, Puyre commented on app/src/main/java/pa/chan/github_integration_proj/data/dto/GitUserDetailsDto.kt
> +data class GitUserDetailsDto(
здесь и в екстеншне префикс Git убрать

2023-02-16 08:53 UTC, Puyre commented on app/src/main/java/pa/chan/github_integration_proj/domain/GetUserDetailsUseCase.kt
> +class GetUserDetailsUseCase(
Юзкейз лучше назвать не по тому действию которое он совершает на уровне data, а по смыслу типа AuthentificateUseCase

2023-02-16 08:53 UTC, Puyre commented on app/src/main/java/pa/chan/github_integration_proj/domain/model/GitUserDetailsModel.kt
> +data class GitUserDetailsModel(
Слишком много слов лишних, лучше просто UserModel

2023-02-16 09:31 UTC, Pogchamb commented
Коммент на втором комите забыл поменять, там исправления после ревью должны быть

2023-02-17 08:18 UTC, Puyre approved these changes

2023-02-17 09:10 UTC, merged