add error handling and rewrite auth methods without username
Pogchamb/github_integration_proj pull request #5
Opened 2023-04-11 07:28 UTC by Pogchamb

2023-04-12 10:06 UTC, Puyre requested changes

2023-04-12 10:06 UTC, Puyre commented on app/src/main/java/pa/chan/github_integration_proj/features/auth/data/AuthRepositoryImpl.kt
>              throw e
вот сюда лучше сделать кастомную ошибочку какую-то с более понтяным название 
Типа ConnectionException, а unknow host я так понимаю будет кидаться если неправильный токен? Тогда должно быть что-то типа InvalidCredentials, чтобы ты выше на юай прокидывал уже не сырые ошибки а конкретные

2023-04-12 10:06 UTC, Puyre commented on app/src/main/java/pa/chan/github_integration_proj/features/auth/presentation/AuthFragment.kt
> +                CustomError.CUSTOM_HTTP_EXCEPTION -> {
слово кастом отсюда лучше убрать, лучше конкретнее типа MateHubError
А еще лучше всего такой ексепшон прям до сюда прокидывать и тут прям ексепшон обрабатывать

2023-04-12 10:06 UTC, Puyre commented on app/src/main/java/pa/chan/github_integration_proj/features/auth/presentation/AuthViewModel.kt
> +                    401 -> _errorLiveData.postValue(CustomError.CUSTOM_HTTP_EXCEPTION)
Вот это должно быть на дата слое только

2023-04-12 10:06 UTC, Puyre commented on app/src/main/java/pa/chan/github_integration_proj/features/auth/presentation/CustomError.kt
> +enum class CustomError(@StringRes val message: Int) {
А если у тебя это обертка над меседжом то тогда зачем тебе что-то кроме месаджа? Можно прям строчку и прокидывать

2023-04-12 10:08 UTC, Niknorov commented on app/src/main/java/pa/chan/github_integration_proj/features/auth/presentation/AuthFragment.kt
> +                CustomError.CUSTOM_HTTP_EXCEPTION -> {
@Puyre А причем тут matehub?)

2023-04-15 09:51 UTC, Puyre commented on app/src/main/java/pa/chan/github_integration_proj/features/auth/presentation/AuthFragment.kt
> +                CustomError.CUSTOM_HTTP_EXCEPTION -> {
Жесть я все перепутал чета)))

2023-04-15 09:54 UTC, Puyre approved these changes

2023-04-15 09:54 UTC, Puyre commented on app/src/main/java/pa/chan/github_integration_proj/features/auth/data/AuthRepositoryImpl.kt
> +        } catch (e: UnknownHostException) {
Вот сюда сделай лучше вместо UnknownHostException просто Exception. Потому что там еще ссл ексепшрн может прилететь, таймаут, и много какой еще
Все это будет ошибка сети просто

2023-04-15 09:54 UTC, Puyre commented on app/src/main/java/pa/chan/github_integration_proj/features/auth/presentation/AuthFragment.kt
> +                Snackbar.make(view, getString(it.errorMessage), Snackbar.LENGTH_INDEFINITE)
лучше для ошибок делать не бесконечный снекбар а коротенький, их в любом случае юзер захочет закрыть а сильно важной инфы там нет

2023-04-15 14:12 UTC, merged